# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZH3ZH92j02UG7he9q9j7CktCsvgJ2cT
"""

# Data Types
# str = string to write/keep text
print("hello 8C")
print('hello 8C')
# numeric types : integer (int), float
print(8.5)
print('8')

# math operator + - / % * (addition, substraction, division, mod, multiplication)
print("8C" + " ms ivonne")
print(3 + 20)
print("3" + "20")

# variables = naming
# in phyton = case sensitive
# ways on write variable = u're not allowed to start with number
# not put space in between
# 8C = 20 -> wrong
# eight c = 20 -> wrong
fried_fish = 100
friedFish = 90
fried_Fish = 65
friedfish = 70
print(friedFish, friedfish)

# input = determinded data types
name = input("please type your name: ")
print("Sooooo ur name is... " ,name, "?")

name = input("please type your name: ")
print("Soooooo ur name is.... " ,name,"?")
age = input("please type your old: ")
print("Sooo ur old is..." ,age, "?")
print ("hi" + " verrence" + " you" + " are" + " 1" + "3" + " years" + " old")